import MainLayout from "./layouts/MainLayout";
import GetRequests from "./pages/request/components/GetRequests";
import NewRequest from "./pages/request/components/NewRequest";
import ListRequests from "./pages/request/components/ListRequests";
import Vehicle from "pages/vehicle/Vehicle";
import OneVehicle from "pages/vehicle/components/OneVehicle";
import AllTabs from "pages/tab/AllTabs";
import OneTab from "pages/tab/OneTab";
import TabTable from "tables/tab/TabTable";
import RequestTable from "tables/request/RequestTable";

const compareFn = (firstPart, secondPart) => {
  const firstPartYear = firstPart.dateRecieved
    ? parseInt(firstPart.dateRecieved.split("-")[2])
    : parseInt(firstPart.dateUsed.split("-")[2]);
  const secondPartYear = secondPart.dateRecieved
    ? parseInt(secondPart.dateRecieved.split("-")[2])
    : parseInt(secondPart.dateUsed.split("-")[2]);
  if (firstPartYear === secondPartYear) {
    const firstPartMonth = firstPart.dateRecieved
      ? parseInt(firstPart.dateRecieved.split("-")[1])
      : parseInt(firstPart.dateUsed.split("-")[1]);
    const secondPartMonth = secondPart.dateRecieved
      ? parseInt(secondPart.dateRecieved.split("-")[1])
      : parseInt(secondPart.dateUsed.split("-")[1]);
    if (firstPartMonth === secondPartMonth) {
      const firstPartDay = firstPart.dateRecieved
        ? parseInt(firstPart.dateRecieved.split("-")[0])
        : parseInt(firstPart.dateUsed.split("-")[0]);
      const secondPartDay = secondPart.dateRecieved
        ? parseInt(secondPart.dateRecieved.split("-")[0])
        : parseInt(secondPart.dateUsed.split("-")[0]);
      if (firstPartMonth === secondPartMonth) {
        return 0;
      }
      return firstPartDay < secondPartDay ? -1 : 1;
    }
    return firstPartMonth < secondPartMonth ? -1 : 1;
  }
  return firstPartYear < secondPartYear ? -1 : 1;
};

const routes = [
  {
    path: "/",
    element: <MainLayout />,
    children: [
      // { path: "request", element: <Request /> },
      { path: "requests/new", element: <NewRequest /> },
      { path: "requests/", element: <GetRequests /> },
      { path: "requests/:phi/:year", element: <ListRequests /> },
      { path: "requests/list", element: <ListRequests /> },

      { path: "tabs", element: <AllTabs /> },
      { path: "tabs/:id", element: <OneTab /> },

      { path: "vehicles", element: <Vehicle /> },
      { path: "vehicles/:id", element: <OneVehicle /> },

      // { path: "customers", element: <CustomerList /> },
      // { path: "dashboard", element: <Dashboard /> },
      // { path: "products", element: <ProductList /> },
      // { path: "settings", element: <Settings /> },
      // { path: "*", element: <Navigate to="/404" /> },
    ],
  },
  {
    path: "/test",
    element: (
      // <TabTable
      //   parts={[
      //     {
      //       dateRecieved: "1-2-2021",
      //       pieNumber: "asdf",
      //       amountRecieved: 2,
      //       tabUsed: "asd",
      //       dateUsed: "2-3-2021",
      //       amountUsed: 1,
      //       id: 1,
      //     },
      //     {
      //       dateRecieved: "1-3-2022",
      //       pieNumber: "3",
      //       amountRecieved: 33,
      //       tabUsed: "",
      //       dateUsed: "",
      //       amountUsed: "",
      //       id: 3,
      //     },
      //     {
      //       dateRecieved: "2-5-2024",
      //       pieNumber: "",
      //       amountRecieved: 10,
      //       tabUsed: "",
      //       dateUsed: "2-5-2020",
      //       amountUsed: 5,
      //       id: 4,
      //     },
      //   ].sort(compareFn)}
      //   startingTotal={100}
      // />
      <RequestTable
        request={{
          firstPartOfPhi: 2,
          secondPartOfPhi: 24,
          year: 24,
          month: 24,
          day: 24,
          id: 1,
          entries: [
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "a",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: 1,
              id: 3,
              parts: [
                {
                  dateRecieved: "78-657-1995",
                  pieNumber: "",
                  amountRecieved: 10,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: 5,
                  id: 4,
                },
              ],
            },
            {
              nameNumber: "aa",
              name: "bb",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: "none",
              id: 5,
            },
            {
              nameNumber: "aa",
              name: "bb",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: "none",
              id: 5,
            },
            {
              nameNumber: "aa",
              name: "bb",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: "none",
              id: 5,
            },
            {
              nameNumber: "aa",
              name: "bb",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: "none",
              id: 5,
            },
            {
              nameNumber: "aa",
              name: "bb",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: "none",
              id: 5,
            },
            {
              nameNumber: "aa",
              name: "bb",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: "none",
              id: 5,
            },
            {
              nameNumber: "aa",
              name: "bb",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: "none",
              id: 5,
            },
            {
              nameNumber: "aa",
              name: "bb",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: "none",
              id: 5,
            },
            {
              nameNumber: "aacc",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: "none",
              id: 6,
              parts: [
                {
                  dateRecieved: "111-111-111",
                  pieNumber: "111",
                  amountRecieved: 111,
                  tabUsed: "111",
                  dateUsed: "111-111-111",
                  amountUsed: 111,
                  id: 6,
                },
              ],
            },
            {
              nameNumber: "asdfab",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: "none",
              id: 7,
            },
            {
              nameNumber: "test",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: "none",
              id: 8,
            },
            {
              nameNumber: "asd",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: "none",
              id: 9,
            },
            {
              nameNumber: "test",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: "none",
              id: 10,
            },
            {
              nameNumber: "testets",
              name: "",
              mainPart: "",
              amountOfOrder: "",
              unitOfOrder: "",
              reasonOfOrder: "",
              priorityOfOrder: "",
              observations: "",
              consumableId: "none",
              id: 11,
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
            {
              nameNumber: "1",
              name: "2",
              mainPart: "3",
              amountOfOrder: 4,
              unitOfOrder: "5",
              reasonOfOrder: 6,
              priorityOfOrder: 7,
              observations: "plate1",
              consumableId: 1,
              id: 1,
              parts: [
                {
                  dateRecieved: "1-2-2021",
                  pieNumber: "asdf",
                  amountRecieved: 2,
                  tabUsed: "asd",
                  dateUsed: "2-3-2021",
                  amountUsed: 1,
                  id: 1,
                },
                {
                  dateRecieved: "1-2-2022",
                  pieNumber: "",
                  amountRecieved: 22,
                  tabUsed: "",
                  dateUsed: "--",
                  amountUsed: "",
                  id: 2,
                },
              ],
            },
          ],
        }}
      />
    ),
    //   children: [
    //     { path: "login", element: <Login /> },
    //     { path: "register", element: <Register /> },
    //     { path: "404", element: <NotFound /> },
    //     { path: "/", element: <Navigate to="/app/dashboard" /> },
    //     { path: "*", element: <Navigate to="/404" /> },
    //   ],
  },
];

export default routes;
